name: flow
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - numpy
  - scipy
  - pandas
  - matplotlib
  - jupyterlab
  - sympy
  - seaborn
  - plotly
  - openpyxl
  - tabulate
  - ipykernel
  - pytest
  - black
  - numba
  - statsmodels
  - pint
  - pip
  - sqlite